### ISSUE TITLE
failed with status: 404 Not

### ISSUE THREAD

**Issue by stkac** [ambroisemaupate/docker-server-env#2]
Hi someone knows how to fix it? thanks 
```
$ docker login registry.example.com
Username: root
Password:
Error response from daemon: login attempt to https://registry.example.com/v2/ failed with status: 404 Not Found
```

**ambroisemaupate/docker-server-env**

**Comment by ambroisemaupate** [comment]
Hi @stkac. 

This is an example registry. That's normal you cannot login. 😁 you should replace it  with your own Registry server.

**Comment by stkac** [comment]
Hi, :D
yes I know, I use this example instead registry.domain.tld ....
but using my real domain docker don't let me sign in

thanks in advance,

**Comment by ambroisemaupate** [comment]
Is it a Gitlab Registry ?

**Comment by ambroisemaupate** [comment]
Do you use your real password or an access-token?

**Comment by stkac** [comment]
I tried with both :)

**Comment by stkac** [comment]
I think it can be an key issue, I get the letsenctrypt acme.json for use the ssl proxy and export this acme.jose in .key .ctl file for each domain...

**Comment by stkac** [comment]
I see you use .pem 
how I can export from .json to .pem?

thanks :)

**Comment by ambroisemaupate** [comment]
Did you verify your registry port ? Did you already succeed to login before ?

**Comment by ambroisemaupate** [comment]
https://discourse.geek-kitchen.funkypenguin.co.nz/t/a-complete-gitlab-traefik-config/554

If you are using Traefik maybe you can use only one container for registry + gitlab. We used nginx-proxy before Traefik so we needed to split containers because of domain names exposition. But with Traefik you can expose multiple ports and domains for one container. I think I will update this compose recipe.

**Comment by stkac** [comment]
Ok, I check it in a few hours, one question: fullchain.pem must have the two public certificates and key.pem the private key or fullchain.pem need include the private too? 
thanks

fullchain.pem
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----


key.pem
-----BEGIN RSA PRIVATE KEY-----
-----END RSA PRIVATE KEY-----

**Comment by ambroisemaupate** [comment]
No fullchain.pem **must not** include your private key in any way. Because fullchain.pem is a public certificate, so you would expose your private key to the client… bad.

**Comment by ambroisemaupate** [comment]
You can add this to your traefik docker-compose to extract Certificates from acme.json

https://github.com/containous/traefik/issues/2418

Then mount `./../traefik/ssl:/etc/gitlab/ssl/` to make them available for registry, mattermost, etc

**Comment by ambroisemaupate** [comment]
Could you try with latest master version 

https://github.com/ambroisemaupate/docker-server-env/tree/master/compose/example-gitlab-traefik

**Comment by stkac** [comment]
ok :)
in 20 min I trie it 
now I get 401 error X)

![image](https://user-images.githubusercontent.com/41887474/55276062-079e7f80-52ef-11e9-8c56-5f93e46c0476.png)
![image](https://user-images.githubusercontent.com/41887474/55276073-2c92f280-52ef-11e9-84c4-b6f4af5bc4fa.png)

**Comment by ambroisemaupate** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/issues/48730

**Comment by stkac** [comment]
yes, that the reason why I create this access token

![image](https://user-images.githubusercontent.com/41887474/55276160-9cee4380-52f0-11e9-8a7d-c2bfb98cbbaf.png)

**Comment by stkac** [comment]
I get this Error form the Registry Container:

```
time="2019-03-30T12:38:45.458368397Z" level=info msg="token signed by untrusted key with ID: "RH64:SMW5:DL6W:PKZT:2ZSE:72N7:JWOG:O7F6:RWGN:IUQX:YZUC:L3PH""
time="2019-03-30T12:38:45.458440996Z" level=warning msg="error authorizing context: invalid token" go.version=go1.11.2 http.request.host=registry.domain.tld http.request.id=adf37de3-cdd5-419d-96e0-0df80be8816f http.request.method=GET http.request.remoteaddr=192.242.188.176 http.request.uri="/v2/" http.request.useragent="docker/18.09.3 go/go1.10.8 git-commit/774a1f4 kernel/4.20.13-200.fc29.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.3 \(linux\))"
172.19.0.2 - - [30/Mar/2019:12:38:45 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/18.09.3 go/go1.10.8 git-commit/774a1f4 kernel/4.20.13-200.fc29.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.3 \\(linux\\))"
time="2019-03-30T12:39:44.333592556Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.11.2 http.request.host=registry.domain.tld http.request.id=ddc33c4a-9b70-4a16-b0a2-3fb47963681f http.request.method=GET http.request.remoteaddr=192.242.188.176 http.request.uri="/v2/" http.request.useragent="docker/18.09.3 go/go1.10.8 git-commit/774a1f4 kernel/4.20.13-200.fc29.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.3 \(linux\))"
172.19.0.2 - - [30/Mar/2019:12:39:44 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/18.09.3 go/go1.10.8 git-commit/774a1f4 kernel/4.20.13-200.fc29.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.3 \\(linux\\))"
time="2019-03-30T12:39:44.933026229Z" level=info msg="token signed by untrusted key with ID: "RH64:SMW5:DL6W:PKZT:2ZSE:72N7:JWOG:O7F6:RWGN:IUQX:YZUC:L3PH""
time="2019-03-30T12:39:44.933106635Z" level=warning msg="error authorizing context: invalid token" go.version=go1.11.2 http.request.host=registry.domain.tld http.request.id=e7fa1b61-04f5-4fdc-83cc-617efaa9bc1d http.request.method=GET http.request.remoteaddr=192.242.188.176 http.request.uri="/v2/" http.request.useragent="docker/18.09.3 go/go1.10.8 git-commit/774a1f4 kernel/4.20.13-200.fc29.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.3 \(linux\))"
172.19.0.2 - - [30/Mar/2019:12:39:44 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/18.09.3 go/go1.10.8 git-commit/774a1f4 kernel/4.20.13-200.fc29.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.3 \\(linux\\))"
```

**Comment by ambroisemaupate** [comment]
I can't reproduce your error: `token signed by untrusted key with ID`. Did you `force-recreate` between config changes?  `docker-compose up -d --force-recreate` 

https://github.com/ambroisemaupate/docker-server-env/blob/master/compose/example-gitlab-traefik/docker-compose.yml

I've just update Traefik + Gitlab + Registry example. It's working on my side. I can login to registry using personal access token and  `/container_registry` project route is working.

**Comment by stkac** [comment]
Hi, I think it's working now but don't know how config mattermost... I need to run the container first without configuring mattermost, then get from the gitlab instance 
        ['gitlab_id']
        ['gitlab_secret']
and then back again fill this data into the docker-compose.yml and recreate it with docker-compose up -d --force-recreate?

![image](https://user-images.githubusercontent.com/41887474/55410981-17bf9480-5565-11e9-83b8-b4ee598f9b41.png)

Thanks in advance, I check your post in 
https://geek-cookbook.funkypenguin.co.nz 
:+1:

**Comment by ambroisemaupate** [comment]
> I need to run the container first without configuring mattermost, then get from the gitlab instance

Yes, I did that. This should not prevent you to access Gitlab in the first place.

**Comment by stkac** [comment]
Ok, and ~~from the admin panel, where I can find this information?~~

I found it :)

![image](https://user-images.githubusercontent.com/41887474/55417042-3b3c0c80-5570-11e9-8722-29055bb0e176.png)

**Comment by ambroisemaupate** [comment]
![image](https://user-images.githubusercontent.com/380026/55417488-172cfb00-5571-11e9-8a5c-c85431fc6040.png)

On Applications > Edit Mattermost

**Comment by ambroisemaupate** [comment]
Hello @stkac 

Is it working ? Gitlab + Registry + Mattermost ?    
Do you have any improvements to suggest on the `example-gitlab-traefik` compose file ? If not I’ll close the issue.

Have a great weekend.

**Comment by stkac** [comment]
Hi @ambroisemaupate 
I ben refactor all my docker-compose based on your work but my containers use the certes created from the original setup stage of gitlab omnibus ... I mounted a shared volume for exchanges between both gitlab and registry containers, it's working from the last 20hs.

I close this issue, in a few days I will share my script too if my installation doesn't get broken before.
